// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ9hP7SPg66wVCSr24Oe3CgAb58hca8eg',
    appId: '1:143155355539:web:7bc5a113a7f42447dd5266',
    messagingSenderId: '143155355539',
    projectId: 'leadership-30b55',
    authDomain: 'leadership-30b55.firebaseapp.com',
    storageBucket: 'leadership-30b55.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw34oQNpKo9cFjCXDx-sl2M_LWLlGZL5A',
    appId: '1:143155355539:android:87d8f512b078a5c9dd5266',
    messagingSenderId: '143155355539',
    projectId: 'leadership-30b55',
    storageBucket: 'leadership-30b55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyvC8TRqlJTcmvgD-ls60KfhPf1Vshpdg',
    appId: '1:143155355539:ios:082b3338d72c190edd5266',
    messagingSenderId: '143155355539',
    projectId: 'leadership-30b55',
    storageBucket: 'leadership-30b55.firebasestorage.app',
    iosBundleId: 'com.example.clickCounter',
  );

}